### ISSUE TITLE
Page regions

### ISSUE THREAD

**Issue by theJenix** [gt-webdev/attendance#102]
It would be great to define "regions" on the page that can be independently updated.  This would allow us to create complex web pages without having to maintain one massive document.

As an example use case, I would like to define a description region at the top left, an events region on the side, an announcements region across the top center.  When I click "edit" on the announcements region, I only see the markdown for that one region and I do not affect the markdown and text for the description and events.

**Comment by thelastnode** [comment]
Maybe way later again, for now, one text field isn't so bad

**Comment by theJenix** [comment]
We may want to revisit this as part of #93, but also as a way to standardize placement of social media tie ins, such as the Facebook like button/box and Twitter follow button.
