### ISSUE TITLE
File upload and storage

### ISSUE THREAD

**Issue by theJenix** [gt-webdev/attendance#103]
The ability to upload files and attach them to the page or an individual event.

Example use cases:

  I would like to host the club logo directly on ccorgs.com.

  I want to upload the club meeting minutes for a specific event, and attach it to the event for future reference.

  I need to distribute a powerpoint slide deck or compiled app or library to the club members.

**Comment by thelastnode** [comment]
Let's mooch! Since everything is public anyways, [imgur](http://imgur.com) for images, description field for minutes, etc., [slideshare](http://slideshare.net)/[scribd](http://scribd.com)/etc for documents.
