### ISSUE TITLE
Automatic links in description markdown

### ISSUE THREAD

**Issue by theJenix** [gt-webdev/attendance#107]
I can create links within the orgs description markdown using the format [text](link title), but not using the automatic links feature (e.g. <link>).  Automatic links are useful for linking email addresses, as it will obfuscate the email address to fool automated scripts and bots bent on sending me junk email.

**Comment by thelastnode** [comment]
Because GitHub parses issues as Markdown, I can't understand this issue, reopen with fixed description

**Comment by theJenix** [comment]
Hey, I fixed the description, but I do not have permissions to reopen.  Do you want to reopen #107 or do you want me to create a new issue?

Jesse Rosalia
GIT MAD, President
Undergraduate Computer Science
Georgia Institute of Technology
jesse.rosalia@gatech.edu

**Comment by thelastnode** [comment]
How will this obfuscate the emails?

**Comment by theJenix** [comment]
I tried to copy and paste the text from daringfireball.net and it was a markdown mess.  Check out http://daringfireball.net/projects/markdown/syntax#autolink

**Comment by thelastnode** [comment]
If this doesn't work out of the box, I think this is more work than it's worth for now. Maybe after we fix/implement all the other things :)

**Comment by theJenix** [comment]
What's bizarre is the discount markdown reference says it should…which probably means you're right...there's a bug in some code we just don't want to be touching right now, haha.

**Comment by theJenix** [comment]
A bit more information on this: It looks like the reason that this doesn't work is because we escape the HTML in the markdown before passing it off to discount.  This is also the reason HTML tags (formatting, layout, iframes) show up in the rendered markdown as plain text (instead of actually affecting the layout of the markdown).  I think escaping the HTML is a good idea from safety, but these other features would be really nice...could we achieve the same security result by removing the call to escape, and then passing the rendered HTML thru whitelist sanitizer to remove malicious links?

**Comment by thelastnode** [comment]
We may want to look at [this](http://code.google.com/p/pagedown/)

**Comment by theJenix** [comment]
Yea that looks pretty sweet...on first glance, exactly what I want for this and a couple other issues.

**Comment by theJenix** [comment]
Reopened to examine pagedown (http://code.google.com/p/pagedown/)

**Comment by thedekel** [comment]
While I was upgrading modules for the move to Express 3.0, I replaced `discount` with `marked` which seems to support automatic linking for anything that's a valid link that looks like `http://*.*.*`. I think this would be sufficient.
