### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by thelastnode** [gt-webdev/attendance#11]
We should test things.

**Comment by ash211** [comment]
Agreed.  There are a lot of unit testing frameworks, the difficulty will be choosing the right one for our needs:

https://github.com/joyent/node/wiki/modules#wiki-testing

**Comment by thelastnode** [comment]
That list doesn't sort by quality or activity, so we'll need to do some manual pruning. We have to do unit testing and some sort of mocks for HTTP requests and database stuff and template rendering, etc.

**Comment by thelastnode** [comment]
[vow.js](http://vowjs.org) is great, used it for alcohol.js, I like it.
