### ISSUE TITLE
Internal server error entering event

### ISSUE THREAD

**Issue by theJenix** [gt-webdev/attendance#113]
I was getting an internal server error when entering an event's start and end time.  Here is the exception trace from my local server instance:
Exception:

```
500 CastError: Cast to date failed for value "2012-01-23 7:30PM"
at SchemaDate.cast (/Users/thejenix/Development/gt-cc/attendance/node_modules/mongoose/lib/schema/date.js:65:9)
at /Users/thejenix/Development/gt-cc/attendance/node_modules/mongoose/lib/document.js:340:27
at model.try (/Users/thejenix/Development/gt-cc/attendance/node_modules/mongoose/lib/document.js:513:8)
at model.set (/Users/thejenix/Development/gt-cc/attendance/node_modules/mongoose/lib/document.js:339:10)
at model.set (/Users/thejenix/Development/gt-cc/attendance/node_modules/mongoose/lib/document.js:293:16)
at model.Document (/Users/thejenix/Development/gt-cc/attendance/node_modules/mongoose/lib/document.js:45:17)
at model.Model (/Users/thejenix/Development/gt-cc/attendance/node_modules/mongoose/lib/model.js:26:12)
at new model (/Users/thejenix/Development/gt-cc/attendance/node_modules/mongoose/lib/model.js:838:11)
at /Users/thejenix/Development/gt-cc/attendance/routes/events.js:21:25
at /Users/thejenix/Development/gt-cc/attendance/node_modules/async/lib/async.js:525:34
```

It appears to fail on the "PM", as 2012-01-23 7:30 works and 2012-01-23 19:30 gets me the correct date. 

I can work around it by using 24 hour time, but it is very un-obvious what the error is and might trip up someone who doesn't have a local copy of the server handy.

**Comment by theJenix** [comment]
This could be considered a complement to #42, except that deals with formatting dates and this is about entering dates.

**Comment by thelastnode** [comment]
The reason this happens is because there needs to be a space between "7:30" and "PM", will be fixed by #42

**Comment by thelastnode** [comment]
This should return a form error actually

**Comment by theJenix** [comment]
Probably, though what would be really cool would be a calendar control, or maybe a javascript enabled text box that prompts you to enter the info in the right format, or accepts "tuesday at 6pm" or something like that.  Then the error will truly be an exception, if there's a bug or any user shenanigans.

**Comment by thelastnode** [comment]
Check the live site now :)

**Comment by theJenix** [comment]
very sweet….can you maybe pre-populate the expected format for time in the time box?  like…instead of it saying time, have it say "Time (ex. hh:mm in 24 hour time)" or something like that.

**Comment by thelastnode** [comment]
Accepts 24 hour format, 12 hour with space AND 12 hour without space,
should work for pretty much every use case, see
f75abe902d5a8a01f58aeef6bb7c3c29677ff7fe

**Comment by theJenix** [comment]
This worked this evening...I had to reenter the date and time for an event and I entered in 6:30PM and 7:30PM, to great success.
