### ISSUE TITLE
Event registration (instead of "check in")

### ISSUE THREAD

**Issue by theJenix** [gt-webdev/attendance#114]
Specifically for big events (not weekly meetings), it would be useful for people to be able to say "I'm attending" so the planners can get a rough count ahead of time (Similar to the Facebook event functionality).  This could also tie into the Facebook import/export, so if you've said Yes on one system, it will reflect your choice on the other.

**Comment by thelastnode** [comment]
wontfix, this is duplicating the functionality that Facebook has
