### ISSUE TITLE
Investigate ways to split app.js into smaller modules

### ISSUE THREAD

**Issue by thelastnode** [gt-webdev/attendance#12]
The app.js file is getting a bit monolithic, what's a reasonable way to split it up?

**Comment by thedekel** [comment]
seperate it by "section" of the app, i.e.

user_handler.js for:
/user
/user/[slug]
/createuser/

orgs_handler.js for:
/orgs
/orgs/[org_hash]
/create_org

etc.

**Comment by thelastnode** [comment]
That's an option, though is that the best choice?

**Comment by thelastnode** [comment]
Broken into modules in `./routes/`, fixed by #31
