### ISSUE TITLE
Dates/times not populated on edit event screen

### ISSUE THREAD

**Issue by theJenix** [gt-webdev/attendance#127]
Child of Issue #113

When I edit an existing event, the date and time boxes are not populated with the previously set values.  Instead, the boxes come up blank.  See this event: http://www.ccorgs.com/events/4f16f5e7dd38750300000067

**Comment by thelastnode** [comment]
Closed by #125

**Comment by thelastnode** [comment]
Dammit, Safari doesn't support `bind`. What the hell Safari.
