### ISSUE TITLE
Change login id terminology

### ISSUE THREAD

**Issue by theJenix** [gt-webdev/attendance#141]
I think we need to change the login id terminology to "CC Orgs ID" or something other than GT Login ID.  I was asked by a faculty member attending our meeting why they were being asked to enter in their GT Login ID and password into an unsecured site, and had to explain that it's a different password than their GT password, and so it won't expose their college credentials.

**Comment by skalnik** [comment]
When this was introduced at WIT, there was similar confusion.

**Comment by thelastnode** [comment]
We should change the _password_ field to be something else, not the login ID, since we want to store the GT ID so we can link it to a student.

**Comment by skalnik** [comment]
Why not store the GT ID as a separate field? It is more complex, but perhaps it would reduce the confusion.

**Comment by thedekel** [comment]
The whole log in/registration method could use a re-haul. People are getting confused as to what to log in with and why their e-mails are not working when they log in, etc. Elevating this to midprio.
