### ISSUE TITLE
Incorrectly calculating dates after february

### ISSUE THREAD

**Issue by theJenix** [gt-webdev/attendance#148]
Dates for events in march are one day off when displayed on the events page.  To reproduce: create an event for March 15 and save the event.  You will see March 16 on the event page.

My guess is there's a bug in how leap year is taken into account...I couldn't see anything obvious on quick glance, though.

**Comment by thelastnode** [comment]
Can't reproduce, seems to be working fine?

**Comment by theJenix** [comment]
Check out this event:
http://www.ccorgs.com/events/4f44fe7111469e0300000064

It display's 3/15 as the date, but if you edit it, you'll see the calendar shows 3/14.

This was observed in Safari 5.1 and Firefox 10.0.2 on Mac.

Jesse Rosalia
GIT MAD, President
Undergraduate Computer Science
Georgia Institute of Technology
jesse.rosalia@gatech.edu

**Comment by thelastnode** [comment]
Oh, gotcha, strange. Maybe because it's at midnight?

**Comment by thelastnode** [comment]
Might also be a timezone issue, though I don't think that's the case, since the timezone is set to east coast

**Comment by thedekel** [comment]
When I looked at the alcohol library I noticed that the tests for it were not passing on a similar issue, it seemed that for some cases the day was off by one. I believe that it is currently fixed.
