### ISSUE TITLE
Kiosk mode

### ISSUE THREAD

**Issue by theJenix** [gt-webdev/attendance#149]
There needs to be an easy way to check in to an event, without logging in (hence, a "kiosk" mode we can use on a common computer).  One idea for implementing this is:
1. User enters email address and GTID directly into event page
   1a. if user exists in database, they are added to the event
   1b. if user does not exist, they get an email thanking them for participating, and inviting them to create an account.
   1b1. if user declines to create an account, the entry of their email address and GTID is kept for club records.
2. the event page will display the first and last name (if an account exists) or email address (if the account does not exist)

**Comment by thedekel** [comment]
Implemented but needs testing in https://github.com/thedekel/attendance/commit/3406d243d4870458553de432eee6bb28f92218e7
