### ISSUE TITLE
Don't show emails publicly for guests

### ISSUE THREAD

**Issue by thelastnode** [gt-webdev/attendance#163]
e.g., http://ccorgs.com/events/50468144d026ad0200000007

**Comment by thelastnode** [comment]
Note the unbreaknow status.

**Comment by thedekel** [comment]
By guest, do you mean someone who isn't logged in, or anyone who isn't an admin?

**Comment by ash211** [comment]
At least those who aren't logged in, those who aren't admins should maybe
just get names like the list higher on the screen.  It's super-easy to grab
huge lists of emails for spamming now, bad bad

**Comment by thedekel** [comment]
How about showing just the part before the "@" to anyone who isn't the org's admin or a super admin?

**Comment by thelastnode** [comment]
Well most of them end in @gatech, so why not just show the first 4
characters and the last character or something? e.g., anki**r@gmail.com

**Comment by thedekel** [comment]
I figured, why not both. #164
