### ISSUE TITLE
Visiting /register while logged in should log you out

### ISSUE THREAD

**Issue by ash211** [gt-webdev/attendance#23]

**Comment by ash211** [comment]
Most likely done somewhere in the guts of the everyauth plugin, though could be done with a custom middleware too.

**Comment by thelastnode** [comment]
I don't think this is the right behavior; I think it should redirect you to the homepage with a flash message of "log out to register".

**Comment by thelastnode** [comment]
Right now, visiting `/register` while logged in gives an error. Looks like an everyauth bug.

**Comment by thedekel** [comment]
got rid of the bug in 1873b61ff, Rather than cause unwanted log-outs, the /recover and /restore page simply ask the user to log out before using those.
