### ISSUE TITLE
Be able to send email

### ISSUE THREAD

**Issue by thelastnode** [gt-webdev/attendance#92]

**Comment by thelastnode** [comment]
wontfix, don't replicate functionality.

**Comment by theJenix** [comment]
What functionality would this replicate?  I'd really like the ability to email the people who attended a given club meeting.

**Comment by thelastnode** [comment]
The actual sending of email, adding a feature to copy all email addresses to clipboard or something might be useful

**Comment by theJenix** [comment]
Ahh yeacan you use mailto: to reference multiple addresses?  If i could get a link that opened my mail client, with all of the checkins in the BCC line, that would solve my issue exactly.
