### ISSUE TITLE
Show recent events under org page

### ISSUE THREAD

**Issue by thelastnode** [gt-webdev/attendance#93]

**Comment by theJenix** [comment]
Where on the page do we want to show recent events?  Should it be based on some tag or markdown, to allow the admins to place it wherever?  Or should we decide on a standardized place for recent events?

**Comment by thelastnode** [comment]
I think it would be good to have a sidebar on the right

**Comment by thedekel** [comment]
implemented in 1873b61ff, might be moved to the side-bar in the future.
